name: phd_core
description: A new Flutter package.
version: 0.0.1
author: Phu Huynh
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  sqflite: ^2.0.0+3
  device_info: ^2.0.0
  shared_preferences: ^2.0.5
  rxdart: ^0.26.0
  get_it: ^6.0.0
  uuid: ^3.0.2
  global_configuration: ^2.0.0-nullsafety.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: