name: phd_core
description: A new Flutter package.
version: 0.0.2
author: Phu Huynh
homepage: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  sqflite: ^2.0.0+3
  device_info: ^2.0.2
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  get_it: ^7.2.0
  uuid: ^3.0.4
  path_provider: ^2.0.2
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  json_annotation: ^4.0.1
  flutter_secure_storage: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: