name: phd_core
description: A new Flutter package.
version: 1.0.0
homepage: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.3
  sqflite: ^2.0.0+4
  device_info: ^2.0.3
  shared_preferences: ^2.0.9
  rxdart: ^0.27.3
  get_it: ^7.2.0
  uuid: ^3.0.5
  path_provider: ^2.0.7
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  json_annotation: ^4.3.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: